#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat Aug 22 19:44:36 NZST 2026
maven-metadata-central.xml.lastUpdated=1787384676300
maven-metadata-public.xml.lastUpdated=1787384676300
